### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mguymon** [swipely/dynamo-local-ruby#5]
@peakxu can you push a new release, i bumped the version to 0.3.0

**Comment by peakxu** [comment]
@mguymon, done. https://rubygems.org/gems/dynamo-local-ruby/versions/0.3.0

**Comment by mguymon** [comment]
u should be sleeping!

**Comment by peakxu** [comment]
@mguymon, it's like 4AM local time. Rise and shine!

BTW, can you let the others know that internet connectivity is kinda wonky for me. Can't seem to hit Slack now. Was able to get to it from hotel. Opposite situation w/ VPN. Surprisingly, GitHub comments seem like most reliable way to communicate for me.

In case it matters, can you ask IT for me to check if they can whitelist 122.96.31.10? That's my IP for the next few weeks.

**Comment by mguymon** [comment]
@peakxu I will pass it along, get some rest. I want pics or I am going to spread rumors you are just at a motel down the road.
