### ISSUE TITLE
Figure out how to get Peak connectivity from China

### ISSUE THREAD

**Issue by joshchu** [swipely/dynamo-local-ruby#6]
Ideas:
- satellite interwebs
- tell Li Keqiang to punch a hole in his human firewall
- establish our own intercontinental line direct to @peakxu's brain
- if all else fails, resort to smoke signals :smoking: 

enlisting the help of @mguymon @danhodge @dstuebe @adamjt to make this happen.

**Comment by adamjt** [comment]
Working on transcontinental vape clouds now.

**Comment by peakxu** [comment]
The world's first Smoke Signals as a Service (SSaaS)? Dig it.

**Comment by joshchu** [comment]
@peakxu - that's now a thing.  Please +1 the PR.

**Comment by peakxu** [comment]
@joshchu, seriously about the firewall. Connections get reset on everything :(. 

For some reason, bundler's request chain gets reset. Installing gems by themselves work. So I end up having to install each gem and move them over.

That direct neural link is sounding better and better.

Examples:

```
Gem::RemoteFetcher::FetchError: Errno::ECONNREFUSED: Connection refused - Connection refused (https://rubygems.org/gems/rspec-3.4.0.gem)
An error occurred while installing rspec (3.4.0), and Bundler cannot continue.
Make sure that `gem install rspec -v '3.4.0'` succeeds before bundling.
[add_all_customers_list_aggregation] ~/git/dotswipely/crm_kinesis gem install rspec -v '3.4.0'
Fetching: rspec-3.4.0.gem (100%)
Successfully installed rspec-3.4.0
1 gem installed
[add_all_customers_list_aggregation] ~/git/dotswipely/crm_kinesis export GEM_NAME=rspec-3.4.0
[add_all_customers_list_aggregation] ~/git/dotswipely/crm_kinesis cp -R /Users/peakxu/.rbenv/versions/jruby-1.7.22/lib/ruby/gems/shared/cache/$GEM_NAME.gem vendor/support/jruby/1.9/cache/
[add_all_customers_list_aggregation] ~/git/dotswipely/crm_kinesis cp -R /Users/peakxu/.rbenv/versions/jruby-1.7.22/lib/ruby/gems/shared/gems/$GEM_NAME vendor/support/jruby/1.9/gems/$GEM_NAME
[add_all_customers_list_aggregation] ~/git/dotswipely/crm_kinesis bivb
```

https://gist.github.com/d5062a538d3deff2f294

**Comment by joshchu** [comment]
@bfulton - ideas on this?

**Comment by peakxu** [comment]
Managed to eventually work through this. Latest pull updated a whole pile of dependencies much like the Dockly one did. Those types of updates currently take me about 4 hours to work through rather than a few minutes if I was in Boston :(

Would certainly appreciate it if you guys can think of a faster way to get the dependencies through. 

Toying w/ idea of just uploading a giant zipped tarball of local bundler vendor directory (possibly split into parts to make it easier to retry downloads)?

**Comment by bfulton** [comment]
@peakxu, is ssh stable? Can you ssh to an EC2 instance and develop from there?

**Comment by peakxu** [comment]
@bfulton, good call. Just tried it out. SSH seems to work. Will use that as a backup next time.

**Comment by joshchu** [comment]
@peakxu - do you have time today by chance to talk CRM interfaces in dynamo? https://trello.com/c/PYSjOjaH/2288-domain-object-best-practices-for-accessing-dynamo-data-3

**Comment by joshchu** [comment]
@peakxu - can you confirm that the ssh port forwarding works for you?  Would like to connect on slack sometime later tonight if possible.  Also, want to confirm if you have a stable network and if you can send the subnet info to @bfulton.

**Comment by peakxu** [comment]
@joshchu, regarding the domain object best practices for Dynamo. Sent out my work on list aggregates in https://github.com/dotswipely/crm_kinesis/pull/6 and got some good feedback from @danhodge regarding our thoughts on models (https://github.com/dotswipely/crm_kinesis/pull/6#discussion_r44955224). I'll be making changes to that effect and adding some paginated access support and then I think we can declare victory on that card.

Regarding SSH, I confirmed I can SSH into an EC2 instance in us-east-1. Haven't been playing with SSH port forwarding thus far. Will do so now and/or try to figure out how to get Slack working. Network here is stable but slow and random sites get connection reset all the time. Slack haven't been working for me.

**Comment by peakxu** [comment]
@joshchu Root issue for both Rubygems and Slack appears to be that a major CDN `global.ssl.fastly.net` gets connection resetted.

https://community.fastly.com/t/fastly-cdn-content-blocked-by-the-great-firewall-of-china/447

Given the answer, I wonder if it's possible to ping Slack and have them take it up w/ Fastly. /cc @bfulton

**Comment by peakxu** [comment]
@bfulton, @joshchu, port forwarding gets blocked as well.

Thoughts on enabling a gateway? https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP

My attempts at accessing Slack primarily fails on loading CDN assets. I suspect the raw underlying communication might work.

**Comment by bfulton** [comment]
Not port forwarding. Ssh web proxy plus slack web client.

**Comment by bfulton** [comment]
Like, `ssh -D 1234 ec2-inst` then going to System Preferences > Network >  Advanced > Proxies > SOCKS Proxy and filling out `localhost` and `1234`.

**Comment by peakxu** [comment]
Shoulda been precise w/ my terminology. I was doing SSH web proxy.

Yep, I've been doing ssh -ND 1080 ec2-user@ec2inst.

I've been using `--proxy-server="socks5://localhost:1080"` argument to Chrome. But that might not have taken as expected. Will try the system proxy method you outlined.

**Comment by joshchu** [comment]
@peakxu - another option is to use a Windows ec2 instance for email and slack only. I have creds but where should I send them to?

**Comment by bfulton** [comment]
@peakxu slacked me shortly after his earlier comment to say that the OS proxy settings worked for Chrome. Can we close this?

**Comment by joshchu** [comment]
@bfulton - nice. It's actually closed right now so think we are all set. Thanks!

**Comment by bfulton** [comment]
Ah. Cool.

**Comment by peakxu** [comment]
:+1:

**Comment by peakxu** [comment]
Also, my initial hunch about only the CDN being blocked proved correct. I was able to grab all the CDN assets using the web proxy and serve them from my local filesystem.

Using a hosts file redirection for the slack CDN, I'm now able to get to Slack w/o needing the web proxy, hurray for skipping trans-pacific ping for every web request.

**Comment by joshchu** [comment]
@peakxu - are you around?  Would like to discuss https://trello.com/c/FnhEjgXY/2219-ticket-based-portal-phase-1-gross-sales-summary-variant-front-end-3 if you get a chance to pop onto slack.
