### ISSUE TITLE
release 0.3.0 is missing jars

### ISSUE THREAD

**Issue by mguymon** [swipely/dynamo-local-ruby#7]
@peakxu 

The 0.3.0 release is missing the dynamno jars

**Comment by peakxu** [comment]
Weird, will rebuild.

**Comment by mguymon** [comment]
weirder, you should be :sleeping:

**Comment by peakxu** [comment]
Why sleep when you can have caffeine? Yanked v0.3.0. Built 0.3.1 and checked it has the Jars. It's just uploading very slowly now :turtle: . Will update when it's done.

**Comment by mguymon** [comment]
+:coffee:

**Comment by peakxu** [comment]
@mguymon, v0.3.1 released w/ Jars.
